return function()
	local ReplicatedStorage = game:GetService("ReplicatedStorage")
	local StatMath = require(ReplicatedStorage.Shared.Formulas.StatMath)

	describe("StatMath.ComputeStats", function()
		it("known input (level 1, no accessories) produces known output", function()
			local stats = StatMath.ComputeStats(1, {})
			expect(stats.HP).to.equal(100)
			expect(stats.Attack).to.equal(10)
			expect(stats.Defense).to.equal(5)
			expect(stats.Stamina).to.equal(100)
			expect(stats.UltimateChargeRate).to.equal(1.0)
		end)

		it("known input (level 5, no accessories) produces known output", function()
			local stats = StatMath.ComputeStats(5, {})
			expect(stats.HP).to.equal(100 + 4 * 15)
			expect(stats.Attack).to.equal(10 + 4 * 2)
			expect(stats.Defense).to.equal(5 + 4 * 1)
			expect(stats.Stamina).to.equal(100 + 4 * 3)
			expect(stats.UltimateChargeRate).to.equal(1.0)
		end)

		it("adds equipped accessory bonuses to HP/Attack/Defense only (GDD §4.1)", function()
			local stats = StatMath.ComputeStats(1, { 3, 3 })
			expect(stats.HP).to.equal(100 + 6)
			expect(stats.Attack).to.equal(10 + 6)
			expect(stats.Defense).to.equal(5 + 6)
			expect(stats.Stamina).to.equal(100)
			expect(stats.UltimateChargeRate).to.equal(1.0)
		end)

		it("is deterministic for the same input", function()
			local a = StatMath.ComputeStats(7, { 1, 2, 3 })
			local b = StatMath.ComputeStats(7, { 1, 2, 3 })
			expect(a.HP).to.equal(b.HP)
			expect(a.Attack).to.equal(b.Attack)
		end)
	end)
end
